name: nebula
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^6.1.2
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_sdl: ^0.10.1
  ffi: ^2.0.1
  image: ^3.2.0
  vector_math: ^2.1.3

dependency_overrides:
  ffi: ^2.0.1
